'use strict';
const token=document.querySelector('meta[name="agentstack-token"]').content;
const base=document.querySelector('meta[name="agentstack-base"]').content;
const state={catalog:null,inventory:null,plan:null,selected:new Set(),profile:'core',allowCredentials:false,allowUpgrades:false,providerOverrides:{}};
const $=id=>document.getElementById(id);
const api=async(path,options={})=>{const opts={...options,headers:{...(options.headers||{}),'X-AgentStack-Token':token}};if(opts.body){opts.headers['Content-Type']='application/json'}const response=await fetch(`${base}api/${path}`,opts);const data=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok){const error=new Error(data.error||`HTTP ${response.status}`);error.data=data;throw error}return data};
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`toast visible${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',4200)}
function tierLabel(tier){return {'essential':'Essential','recommended':'Recommended enrichment','optional-local':'Optional local','credential':'Credential / login'}[tier]||tier}
function invalidatePlan(){state.plan=null;$('confirmApply').checked=false;$('applyBtn').disabled=true;$('planContent').hidden=true;$('planEmpty').hidden=false;$('planEmpty').textContent='Selections changed. Build and review a new plan before applying.'}
function applyProfile(){const profile=state.catalog.profiles.find(p=>p.id===state.profile);state.selected=new Set(profile?profile.components:[]);state.providerOverrides={};$('browserProvider').value='';invalidatePlan();renderComponents();updateMetrics()}
function buildRequest(){const profile=state.catalog.profiles.find(p=>p.id===state.profile)||{components:[]};const defaults=new Set(profile.components);const include=[...state.selected].filter(id=>!defaults.has(id));const exclude=[...defaults].filter(id=>!state.selected.has(id));return {profile:state.profile,include,exclude,allowCredentialed:state.allowCredentials,allowUpgrades:state.allowUpgrades,providerOverrides:state.providerOverrides}}
function updateMetrics(){if(!state.inventory||!state.catalog)return;const installed=Object.values(state.inventory.items||{}).filter(x=>x.installed).length;$('detectedMetric').textContent=installed;$('preservedMetric').textContent=installed;$('selectedMetric').textContent=state.selected.size;$('credentialMetric').textContent=state.allowCredentials?'On':'Off'}
function renderProfiles(){const select=$('profileSelect');select.innerHTML=state.catalog.profiles.map(p=>`<option value="${escapeHtml(p.id)}">${escapeHtml(p.name)} — ${escapeHtml(p.description)}</option>`).join('');if(!state.catalog.profiles.some(p=>p.id===state.profile)){state.profile=state.catalog.profiles[0]?.id||'custom'}select.value=state.profile}
function renderProviders(){const providers=state.catalog.components.filter(c=>c.capability==='browser');$('browserProvider').innerHTML=`<option value="">No browser provider selected</option>`+providers.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.name)}${c.preferred?' (recommended)':''}</option>`).join('');$('browserProvider').value=state.providerOverrides.browser||''}
function renderComponents(){if(!state.catalog)return;const query=$('componentSearch').value.toLowerCase().trim();const groups=['essential','recommended','optional-local','credential'];$('componentGroups').innerHTML=groups.map(tier=>{const items=state.catalog.components.filter(c=>c.tier===tier).filter(c=>!query||`${c.name} ${c.description} ${c.category} ${c.capability||''}`.toLowerCase().includes(query));if(!items.length)return'';return `<section class="component-group"><h3>${tierLabel(tier)}</h3><div class="component-grid">${items.map(componentCard).join('')}</div></section>`}).join('');document.querySelectorAll('.component-card input').forEach(input=>input.addEventListener('change',event=>{const id=event.target.dataset.id;if(event.target.checked)state.selected.add(id);else state.selected.delete(id);invalidatePlan();renderComponents();updateMetrics()}))}
function componentCard(c){const inv=state.inventory?.items?.[c.id];const installed=!!inv?.installed;const broken=!!inv?.broken;const incompatible=!!inv?.incompatible;const checked=state.selected.has(c.id);const disabled=c.credentialRequired&&!state.allowCredentials;const health=(broken||incompatible)&&inv?.healthMessage?` title="${escapeHtml(inv.healthMessage)}"`:'';const hint=c.install?.loginHint?`<p class="login-hint">Next: ${escapeHtml(c.install.loginHint)}</p>`:'';return `<label class="component-card ${checked?'selected':''} ${disabled?'disabled':''}"${health}><input type="checkbox" data-id="${escapeHtml(c.id)}" ${checked?'checked':''} ${disabled?'disabled':''}><div><h4>${escapeHtml(c.name)}</h4><p>${escapeHtml(c.description)}</p>${hint}<div class="card-meta"><span class="badge">${escapeHtml(c.category)}</span>${broken?'<span class="badge repair">repair available</span>':incompatible?'<span class="badge repair">upgrade approval needed</span>':installed?'<span class="badge installed">installed</span>':''}${c.credentialRequired?'<span class="badge credential">guided login</span>':''}${c.preferred?'<span class="badge">preferred</span>':''}</div></div></label>`}
function renderPlan(plan){state.plan=plan;$('planEmpty').hidden=true;$('planContent').hidden=false;const counts={};plan.actions.forEach(a=>counts[a.kind]=(counts[a.kind]||0)+1);$('planSummary').innerHTML=Object.entries(counts).map(([kind,count])=>`<article><span>${escapeHtml(kind)}</span><strong>${count}</strong><small>components</small></article>`).join('');$('planRows').innerHTML=plan.actions.map(a=>`<tr><td><strong>${escapeHtml(a.name||a.componentId)}</strong><br><small>${escapeHtml(a.componentId)}</small></td><td><span class="action-pill ${escapeHtml(a.kind)}">${escapeHtml(a.kind)}</span></td><td>${escapeHtml(a.reason)}</td></tr>`).join('');$('confirmApply').checked=false;$('applyBtn').disabled=true;showSection('plan')}
function showSection(id,focus=true){document.querySelectorAll('.section').forEach(el=>{const active=el.id===id;el.classList.toggle('active-section',active);el.hidden=!active});document.querySelectorAll('.nav-item').forEach(el=>{const active=el.dataset.section===id;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});if(focus){const heading=document.querySelector(`#${id} h2`);if(heading)heading.focus()}}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
async function refresh(){try{[state.catalog,state.inventory]=await Promise.all([api('catalog'),api('inventory')]);renderProfiles();renderProviders();applyProfile();renderComponents();toast('Inventory refreshed')}catch(error){toast(error.message,true)}}
async function buildPlan(){try{const plan=await api('plan',{method:'POST',body:JSON.stringify(buildRequest())});renderPlan(plan);toast('Reviewed plan generated')}catch(error){toast(error.message,true)}}
async function applyPlan(){if(!$('confirmApply').checked||!state.plan)return;try{$('applyBtn').disabled=true;const report=await api('apply',{method:'POST',body:JSON.stringify({planId:state.plan.id,digest:state.plan.digest,confirm:true})});$('routerOutput').textContent=JSON.stringify(report,null,2);toast('Reviewed plan applied and postconditions verified');await refresh()}catch(error){$('routerOutput').textContent=JSON.stringify(error.data||{error:error.message},null,2);toast(error.message,true)}finally{$('confirmApply').checked=false;$('applyBtn').disabled=true}}
async function mcpInit(){if(!window.confirm('Initialize the selected MCP profile, write AgentStack-managed router configuration, and repair owned client registrations?'))return;try{const report=await api('mcp/init',{method:'POST',body:JSON.stringify({request:buildRequest(),registerClients:true,warm:true,confirm:true})});$('routerOutput').textContent=JSON.stringify(report,null,2);showSection('router');toast('MCP stack initialized')}catch(error){$('routerOutput').textContent=JSON.stringify(error.data||{error:error.message},null,2);showSection('router');toast(error.message,true)}}
async function doctor(){try{const report=await api('mcp/doctor');$('routerOutput').textContent=JSON.stringify(report,null,2);showSection('router');toast(report.healthy?'MCP doctor passed':'MCP doctor found issues',!report.healthy)}catch(error){$('routerOutput').textContent=JSON.stringify(error.data||{error:error.message},null,2);showSection('router');toast(error.message,true)}}
async function installSelf(){if(!window.confirm('Install the verified AgentStack console binary into the user application directory and update the user PATH?'))return;try{const report=await api('install-self',{method:'POST',body:JSON.stringify({confirm:true})});toast(report.pathChanged?'Installed and added to PATH':'AgentStack installation is already current')}catch(error){toast(error.message,true)}}
async function shutdown(){try{await api('shutdown',{method:'POST',body:'{}'});document.querySelector('main').innerHTML='<section class="empty-state"><h2>AgentStack Manager stopped</h2><p>You can close this browser tab.</p></section>'}catch(error){toast(error.message,true)}}
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>showSection(button.dataset.section,true)));
$('profileSelect').addEventListener('change',event=>{state.profile=event.target.value;applyProfile()});
$('credentialToggle').addEventListener('change',event=>{state.allowCredentials=event.target.checked;if(!state.allowCredentials){state.catalog.components.filter(c=>c.credentialRequired).forEach(c=>state.selected.delete(c.id))}invalidatePlan();renderComponents();updateMetrics()});
$('upgradeToggle').addEventListener('change',event=>{state.allowUpgrades=event.target.checked;invalidatePlan()});
$('browserProvider').addEventListener('change',event=>{if(event.target.value){state.providerOverrides.browser=event.target.value;state.selected.add(event.target.value)}else{delete state.providerOverrides.browser}invalidatePlan();renderComponents()});
$('componentSearch').addEventListener('input',renderComponents);
$('refreshBtn').addEventListener('click',refresh);$('buildPlanBtn').addEventListener('click',buildPlan);$('applyBtn').addEventListener('click',applyPlan);$('confirmApply').addEventListener('change',event=>$('applyBtn').disabled=!event.target.checked||!state.plan);$('mcpInitBtn').addEventListener('click',mcpInit);$('doctorBtn').addEventListener('click',doctor);$('mcpDoctorBtn').addEventListener('click',doctor);$('installSelfBtn').addEventListener('click',installSelf);$('exitBtn').addEventListener('click',shutdown);
showSection('overview',false);refresh();
